### ISSUE TITLE
newline rendering issue between bullets

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#221]
Newlines between bullets are inserting a `<p>` tag inside of the `<li>` tag which leads to incorrect formatting of bullets. 

Noticed this when creating https://lbry.io/faq/startup-troubleshooting originally and I had newlines between the bullets. Removing them fixed the issue but the renderer should be able to handle this situation correctly. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by KamilPiekutowski** [comment]
Does this still need to be resolved?

**Comment by tzarebczan** [comment]
It's a minor annoyance, but sure!

**Comment by KamilPiekutowski** [comment]
MY browser does not show any <p< in between <li>s. Is there something I am missing?

**Comment by jsigwart** [comment]
Is this still an issue? It looks like there is 24px of margin space between list items. Is there a need for newlines within the list items?

**Comment by kauffj** [comment]
I think I fixed this without realizing there was a ticket for it. @tzarebczan can you confirm this issue is resolved?

**Comment by tzarebczan** [comment]
Nope, still happening and Brinck ran into it recently when creating https://github.com/lbryio/lbry.io/blob/master/content/news/158-LBRY-in-2017-2018.md which had bullets. 

To reproduce, edit that file locally to insert new lines between the bullets. 

![bullets](https://user-images.githubusercontent.com/8120721/35938490-3aec819a-0c17-11e8-929a-2037ee423505.png)


The page source looks like:
```

<li>Over 100 developers have contributed to the LBRY code base, over 4,000 developers follow the project, and LBRY is continually rated one of the most active projects in blockchain. For example, we’re in the top 20 on CoinGecko, despite it only counting one of several core codebases!</li>
<li>
<p>We grew from a lean 5 employees to <a href="https://lbry.io/team">14 employees</a> on five continents.</p>
</li>
```

**Comment by alyssaoc** [comment]
@tzarebczan is this still an issue?

**Comment by alyssaoc** [comment]
@NetOperatorWibby said its fixed
