### ISSUE TITLE
Docker install fails for both Linux & OSX

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbry.com#373]
When I try to run lbry.io under Docker on OSX I get the following error.

> /docker.sh 
> Unable to find image 'php:7-alpine' locally
> docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/php/manifests/7-alpine: unauthorized: incorrect username or password.
> 

When I try running it on Lubuntu 16.04.3 LTS under Virtual Box I get the following errors:

Doesn't like being run via an ssh tunnel ...

<img width="795" alt="failure-tunnel" src="https://user-images.githubusercontent.com/36087921/35998883-d2736c8e-0cd2-11e8-89f2-6f34442abd1d.png">

Also doesn't want to run in a browser on the VM hosting it ...

<img width="824" alt="failure-direct" src="https://user-images.githubusercontent.com/36087921/35998915-f3bb3ea8-0cd2-11e8-9b2f-fe66035c5bf5.png">

My OSX Docker is Version 17.12.0-ce-mac49 (21995)

My Lubuntu Docker is  docker.io  1.13.1-0ubuntu1~16.04.2

**Comment by kauffj** [comment]
I merged #383 - what aspect of this problem is macOS specific?

**Comment by seanyesmunt** [comment]
Still seeing this issue.

The server seems to startup fine, but when I go to `localhost:8000`, I see a similar error:
```
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'index.php' (include_path='.:') in Unknown on line 0
```

The non-docker setup seems to work fine.
